# Generated by Django 3.2.7 on 2022-06-01 07:28

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('batch_num', models.IntegerField()),
                ('image', models.ImageField(upload_to=api.models.upload_path)),
            ],
        ),
    ]
